/**
 * Back-compat: CacheService must open and read a cache database FILE
 * created by better-sqlite3 (the storage backend up to v1.x). This is
 * the one place real user data is at risk in the node:sqlite migration.
 *
 * The fixture (tests/fixtures/cache-better-sqlite3.db) was generated by
 * better-sqlite3 12.11.1 (SQLite 3.53.2) mirroring CacheService's real
 * on-disk layout: WAL journal mode, user_version = 1, cache table with
 * timestamp index, three rows stamped 2026-07-01T00:00:00Z.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { CacheService } from '../../src/storage/cache';

const FIXTURE = path.join(__dirname, '..', 'fixtures', 'cache-better-sqlite3.db');

describe('CacheService better-sqlite3 back-compat', () => {
  let testCacheDir: string;
  let testCachePath: string;
  let cache: CacheService | undefined;

  beforeEach(() => {
    testCacheDir = fs.mkdtempSync(path.join(os.tmpdir(), 'deepl-cli-backcompat-'));
    testCachePath = path.join(testCacheDir, 'cache.db');
    fs.copyFileSync(FIXTURE, testCachePath);
  });

  afterEach(() => {
    cache?.close();
    cache = undefined;
    fs.rmSync(testCacheDir, { recursive: true, force: true });
  });

  function openFixture(): CacheService {
    // ttl: 0 disables expiry so the fixture's fixed timestamps stay readable.
    cache = new CacheService({ dbPath: testCachePath, ttl: 0 });
    return cache;
  }

  it('opens the database without treating it as corrupt', () => {
    openFixture();

    const corruptBackups = fs.readdirSync(testCacheDir).filter((f) => f.includes('.corrupt-'));
    expect(corruptBackups).toEqual([]);
  });

  it('reads all entries written by better-sqlite3', () => {
    const service = openFixture();

    expect(service.get('translate:v1:hello')).toEqual({
      text: 'Hallo',
      detectedSourceLang: 'en',
    });
    expect(service.get('translate:v1:world')).toEqual({
      text: 'Welt',
      detectedSourceLang: 'en',
    });
    expect(service.get('write:v1:improve')).toEqual({ text: 'An improved sentence.' });
  });

  it('reports accurate stats for the pre-existing entries', () => {
    const service = openFixture();

    const stats = service.stats();
    expect(stats.entries).toBe(3);
    expect(stats.totalSize).toBeGreaterThan(0);
  });

  it('writes new entries alongside the old ones', () => {
    const service = openFixture();

    service.set('translate:v1:new', { text: 'Neu' });

    expect(service.get('translate:v1:new')).toEqual({ text: 'Neu' });
    expect(service.get('translate:v1:hello')).toEqual({
      text: 'Hallo',
      detectedSourceLang: 'en',
    });
    expect(service.stats().entries).toBe(4);
  });

  it('survives a close and reopen cycle', () => {
    const service = openFixture();
    service.set('translate:v1:new', { text: 'Neu' });
    service.close();
    cache = undefined;

    const reopened = openFixture();
    expect(reopened.get('translate:v1:new')).toEqual({ text: 'Neu' });
    expect(reopened.stats().entries).toBe(4);
  });
});
