import type { Formality } from '../types/common.js';
import type { ModelType } from '../types/api.js';

// --- Sync Configuration ---

export interface SyncLocaleOverrides {
  formality?: Formality;
  glossary?: string;
  translation_memory?: string;
  translation_memory_threshold?: number;
  custom_instructions?: string[];
  style_id?: string;
}

export interface SyncTranslationSettings {
  formality?: Formality;
  model_type?: ModelType;
  glossary?: string;
  translation_memory?: string;
  translation_memory_threshold?: number;
  custom_instructions?: string[];
  style_id?: string;
  locale_overrides?: Record<string, SyncLocaleOverrides>;
  instruction_templates?: Record<string, string>;
  length_limits?: {
    enabled?: boolean;
    expansion_factors?: Record<string, number>;
  };
}

export interface SyncContextSettings {
  enabled: boolean;
  scan_paths?: string[];
  function_names?: string[];
  context_lines?: number;
  overrides?: Record<string, string>;
}

export interface SyncValidationSettings {
  check_placeholders?: boolean;
  fail_on_error?: boolean;
  validate_after_sync?: boolean;
  fail_on_missing?: boolean;
  fail_on_stale?: boolean;
}

export interface SyncLimits {
  max_entries_per_file?: number;
  max_file_bytes?: number;
  max_depth?: number;
  /**
   * Maximum number of source files a single bucket's `include` glob may
   * match before the bucket is skipped with a warning. Guards against a
   * misconfigured `**\/*.json` that accidentally picks up a vendored tree.
   * Default 10_000 keeps legitimate large-i18n projects working while
   * flagging obvious cardinality explosions.
   */
  max_source_files?: number;
}

export interface SyncBehavior {
  concurrency: number;
  batch_size: number;
  max_characters?: number;
  backup?: boolean;
  batch?: boolean;
  max_scan_files?: number;
  bak_sweep_max_age_seconds?: number;
  /**
   * Per-file parser caps, applied format-agnostically. Default-exceed =
   * file-skip + warn; setting any value above the hard ceiling fails at
   * config load with a ConfigError.
   * See {@link DEFAULT_SYNC_LIMITS} and {@link HARD_MAX_SYNC_LIMITS}.
   */
  limits?: SyncLimits;
}

export interface SyncBucketConfig {
  include: string[];
  exclude?: string[];
  key_style?: 'nested' | 'flat';
  target_path_pattern?: string;
}

export interface SyncConfig {
  version: number;
  source_locale: string;
  target_locales: string[];
  buckets: Record<string, SyncBucketConfig>;
  translation?: SyncTranslationSettings;
  context?: SyncContextSettings;
  validation?: SyncValidationSettings;
  sync?: SyncBehavior;
  ignore?: string[];
  tms?: SyncTmsConfig;
}

export interface SyncTmsConfig {
  enabled: boolean;
  server: string;
  project_id: string;
  api_key?: string;
  token?: string;
  auto_push?: boolean;
  auto_pull?: boolean;
  require_review?: string[];
  timeout_ms?: number;
  push_concurrency?: number;
}

// --- Lock File ---

export interface SyncLockTranslation {
  hash: string;
  translated_at: string;
  model_type?: ModelType;
  character_count?: number;
  context_sent?: boolean;
  status: 'translated' | 'failed' | 'pending';
  review_status?: 'machine_translated' | 'human_reviewed';
  reviewed_in?: string;
}

export interface SyncLockEntry {
  source_hash: string;
  source_text: string;
  translations: Record<string, SyncLockTranslation>;
}

export interface SyncLockStats {
  total_keys: number;
  total_translations: number;
  last_sync: string;
}

export interface SyncLockFile {
  _comment: string;
  version: number;
  generated_at: string;
  source_locale: string;
  entries: Record<string, Record<string, SyncLockEntry>>;
  stats: SyncLockStats;
  glossary_ids?: Record<string, string>;
}

// --- Diff Engine ---

export type SyncDiffStatus = 'new' | 'stale' | 'current' | 'deleted';

export interface SyncDiff {
  key: string;
  status: SyncDiffStatus;
  value?: string;
  previous_hash?: string;
  metadata?: Record<string, unknown>;
}

export interface SyncStatusLocale {
  complete: number;
  missing: number;
  outdated: number;
}

export interface SyncStatus {
  file_path: string;
  total_keys: number;
  per_locale: Record<string, SyncStatusLocale>;
}

// --- Constants ---

export const LOCK_FILE_VERSION = 1;
export const LOCK_FILE_NAME = '.deepl-sync.lock';
export const LOCK_FILE_COMMENT =
  'Auto-generated by deepl sync. To resolve merge conflicts, accept either version and re-run deepl sync.';

// --- Default Sync Behavior ---

export const DEFAULT_SYNC_BEHAVIOR: SyncBehavior = {
  concurrency: 5,
  batch_size: 50,
};

// --- Parser caps ---

export const DEFAULT_SYNC_LIMITS: Required<SyncLimits> = {
  max_entries_per_file: 25_000,
  max_file_bytes: 4 * 1024 * 1024, // 4 MiB
  max_depth: 32,
  max_source_files: 10_000,
};

export const HARD_MAX_SYNC_LIMITS: Required<SyncLimits> = {
  max_entries_per_file: 100_000,
  max_file_bytes: 10 * 1024 * 1024, // 10 MiB
  max_depth: 64,
  max_source_files: 1_000_000,
};

export function resolveSyncLimits(config: { sync?: SyncBehavior }): Required<SyncLimits> {
  const user = config.sync?.limits;
  return {
    max_entries_per_file:
      user?.max_entries_per_file ?? DEFAULT_SYNC_LIMITS.max_entries_per_file,
    max_file_bytes: user?.max_file_bytes ?? DEFAULT_SYNC_LIMITS.max_file_bytes,
    max_depth: user?.max_depth ?? DEFAULT_SYNC_LIMITS.max_depth,
    max_source_files:
      user?.max_source_files ?? DEFAULT_SYNC_LIMITS.max_source_files,
  };
}
